config/routes.rb
Rails.application.routes.draw do
  
  # 一般ユーザーで使用するルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: :about
    
    # 投稿記事関連
    resources :items, only: [:index, :show] do
      resource :interests, only: [:create, :destroy] do
        delete 'list_destroy' => 'interests#list_destroy'
      end
      resources :comments, only: [:new, :index, :edit, :update, :create] do
        resource :favorites, only: [:create, :destroy]
      end
      get 'compare' => 'items#compare', as: :compare
      get 'compare/item2_id' => 'items#compare_result', as: :compare_result
    end
    
    # ユーザー関連
    resource :users, only: [:show, :edit, :update] do
      get :check, on: :collection
      get :interests, on: :collection
      patch :withdrawal, on: :collection
    end
    
    # ユーザー側検索関連
    get "search" => "searches#search"
    resources :operation_systems, only: [:show]
    resources :makers, only: [:show]
  end
  
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  # ゲストユーザー用ルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 管理者で使用するルーティング
  namespace :admin do
    root to: "homes#top"
    
    # 投稿記事関連
    resources :items, only: [:new, :create, :show, :edit, :update] do
      resources :comments, only: [:index, :destroy]
    end
    
    resources :categories, only: [:index]
    resources :users, only: [:index, :show, :edit, :update]
    
    # カテゴリー操作
    resources :operation_systems, only: [:create, :edit, :update, :destroy]
    resources :central_processing_units, only: [:create, :edit, :update, :destroy]
    resources :authentications, only: [:create, :edit, :update, :destroy]
    resources :specs, only: [:create, :edit, :update, :destroy]
    resources :makers, only: [:create, :edit, :update, :destroy]
    resources :capacities, only: [:create, :edit, :update, :destroy]
    
    get "search" => "searches#search"
  end
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  # ログイン制限
  before_action :autheniticate_admin, only: [:index]
  
  def index
    # 入力フォーム生成
    @operation_system = OperationSystem.new
    @spec = Spec.new
    @maker = Maker.new
    @capacity = Capacity.new
    @central_processing_unit = CentralProcessingUnit.new
    @authentication = Authentication.new
    
    # 一覧生成
    @operation_systems = OperationSystem.all
    @specs = Spec.all
    @makers = Maker.all
    @capacities = Capacity.all
    @central_processing_units = CentralProcessingUnit.all
    @authentications = Authentication.all
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  
  <div class="row border-bottom border-dark pb-3">
    <h3><strong>カテゴリ新規登録</strong></h3>
  </div>
  
  <div class="container mt-4">
    <div class="row">
      <p><strong>></strong>下記の情報を入力してください。</p>
    </div>
    <%= render "layouts/flash" %>
    <div class="card bg-white p-3">
    
      <!--OSの入力フォーム-->
      <%= form_with model: @operation_system, url: admin_operation_systems_path, method: :post do |f| %>
        <dl class="row mt-3 pb-3 border-bottom">
          <dt class="col-2 pt-1">OS</dt>
          <dd class="col-6"><%= f.text_field :name, class: "form-control", placeholder: "OS名を入力" %></dd>
          <dd class="col-2 text-center"><%= f.submit "登録", class: "font-weight-bold btn btn-warning rounded-0 border border-dark" %></dd>
        </dl>
      <% end %>
      
      <!--スペックの入力フォーム-->
      <%= form_with model: @spec, url: admin_specs_path, method: :post do |f| %>
        <dl class="row mt-3 pb-3 border-bottom">
          <dt class="col-2 pt-1">スペック</dt>
          <dd class="col-6"><%= f.text_field :name, class: "form-control", placeholder: "スペック名を入力" %></dd>
          <dd class="col-2 text-center"><%= f.submit "登録", class: "font-weight-bold btn btn-warning rounded-0 border border-dark" %></dd>
        </dl>
      <% end %>
      
      <!--メーカーの入力フォーム-->
      <%= form_with model: @maker, url: admin_makers_path, method: :post do |f| %>
        <dl class="row mt-3 pb-3 border-bottom">
          <dt class="col-2 pt-1">メーカー</dt>
          <dd class="col-6"><%= f.text_field :name, class: "form-control", placeholder: "メーカー名を入力" %></dd>
          <dd class="col-2 text-center"><%= f.submit "登録", class: "font-weight-bold btn btn-warning rounded-0 border border-dark" %></dd>
        </dl>
      <% end %>
      
      <!--容量の入力フォーム-->
      <%= form_with model: @capacity, url: admin_capacities_path, method: :post do |f| %>
        <dl class="row mt-3 pb-3 border-bottom">
          <dt class="col-2 pt-1">容量</dt>
          <dd class="col-6"><%= f.text_field :name, class: "form-control", placeholder: "容量名を入力" %></dd>
          <dd class="col-2 text-center"><%= f.submit "登録", class: "font-weight-bold btn btn-warning rounded-0 border border-dark" %></dd>
        </dl>
      <% end %>
      
      <!--CPUの入力フォーム-->
      <%= form_with model: @central_processing_unit, url: admin_central_processing_units_path, method: :post do |f| %>
        <dl class="row mt-3 pb-3 border-bottom">
          <dt class="col-2 pt-1">CPU</dt>
          <dd class="col-6"><%= f.text_field :name, class: "form-control", placeholder: "CPU名を入力" %></dd>
          <dd class="col-2 text-center"><%= f.submit "登録", class: "font-weight-bold btn btn-warning rounded-0 border border-dark" %></dd>
        </dl>
      <% end %>
      
      <!--認証の入力フォーム-->
      <%= form_with model: @authentication, url: admin_authentications_path, method: :post do |f| %>
        <dl class="row mt-3">
          <dt class="col-2 pt-1">認証</dt>
          <dd class="col-6"><%= f.text_field :name, class: "form-control", placeholder: "認証名を入力" %></dd>
          <dd class="col-2 text-center"><%= f.submit "登録", class: "font-weight-bold btn btn-warning rounded-0 border border-dark" %></dd>
        </dl>
      <% end %>
      
    </div>
  </div>
  
  <div class="row border-bottom border-dark mt-5 pb-3">
    <h3><strong>カテゴリ一覧</strong></h3>
  </div>
  
  <div class="row mt-5">
    
    <div class="col-2">
      <h6 class="pb-2 border-bottom border-dark"><strong>OS</strong></h6>
      <div class="card bg-white mt-3 p-2">
        <% @operation_systems.each do |operation_system| %>
          <div class="d-flex justify-content-end border-bottom mt-2 pb-2">
            <%= link_to operation_system.name, edit_admin_operation_system_path(operation_system.id), class: "mr-auto" %>
            <%= link_to admin_operation_system_path(operation_system.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                <span class="text-secondary"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="col-2">
      <h6 class="pb-2 border-bottom border-dark"><strong>スペック</strong></h6>
      <div class="card bg-white mt-3 p-2">
        <% @specs.each do |spec| %>
          <div class="d-flex justify-content-end border-bottom mt-2 pb-2">
            <%= link_to spec.name, edit_admin_spec_path(spec.id), class: "mr-auto" %>
            <%= link_to admin_spec_path(spec.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                <span class="text-secondary"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="col-2">
      <h6 class="pb-2 border-bottom border-dark"><strong>メーカー</strong></h6>
      <div class="card bg-white mt-3 p-2">
        <% @makers.each do |maker| %>
          <div class="d-flex justify-content-end border-bottom mt-2 pb-2">
            <%= link_to maker.name, edit_admin_maker_path(maker.id), class: "mr-auto" %>
            <%= link_to admin_maker_path(maker.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                <span class="text-secondary"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="col-2">
      <h6 class="pb-2 border-bottom border-dark"><strong>容量</strong></h6>
      <div class="card bg-white mt-3 p-2">
        <% @capacities.each do |capacity| %>
          <div class="d-flex justify-content-end border-bottom mt-2 pb-2">
            <%= link_to capacity.name, edit_admin_capacity_path(capacity.id), class: "mr-auto" %>
            <%= link_to admin_capacity_path(capacity.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                <span class="text-secondary"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="col-2">
      <h6 class="pb-2 border-bottom border-dark"><strong>CPU</strong></h6>
      <div class="card bg-white mt-3 p-2">
        <% @central_processing_units.each do |central_processing_unit| %>
          <div class="d-flex justify-content-end border-bottom mt-2 pb-2">
            <%= link_to central_processing_unit.name, edit_admin_central_processing_unit_path(central_processing_unit.id), class: "mr-auto" %>
            <%= link_to admin_central_processing_unit_path(central_processing_unit.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                <span class="text-secondary"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="col-2">
      <h6 class="pb-2 border-bottom border-dark"><strong>認証</strong></h6>
      <div class="card bg-white mt-3 p-2">
        <% @authentications.each do |authentication| %>
          <div class="d-flex justify-content-end border-bottom mt-2 pb-2">
            <%= link_to authentication.name, edit_admin_authentication_path(authentication.id), class: "mr-auto" %>
            <%= link_to admin_authentication_path(authentication.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                <span class="text-secondary"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
  </div>
</div>