config/routes.rb
Rails.application.routes.draw do
  
  # 一般ユーザーで使用するルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: :about
    
    # 投稿記事関連
    resources :items, only: [:index, :show] do
      resource :interests, only: [:create, :destroy] do
        delete 'list_destroy' => 'interests#list_destroy'
      end
      resources :comments, only: [:new, :index, :edit, :update, :create] do
        resource :favorites, only: [:create, :destroy]
      end
      get 'compare' => 'items#compare', as: :compare
      get 'compare/item2_id' => 'items#compare_result', as: :compare_result
    end
    
    # ユーザー関連
    resource :users, only: [:show, :edit, :update] do
      get :check, on: :collection
      get :interests, on: :collection
      patch :withdrawal, on: :collection
    end
    
    # ユーザー側検索関連
    get "search" => "searches#search"
    resources :operation_systems, only: [:show]
    resources :makers, only: [:show]
  end
  
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  # ゲストユーザー用ルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 管理者で使用するルーティング
  namespace :admin do
    root to: "homes#top"
    
    # 投稿記事関連
    resources :items, only: [:new, :create, :show, :edit, :update] do
      resources :comments, only: [:index, :destroy]
    end
    
    resources :categories, only: [:index]
    resources :users, only: [:index, :show, :edit, :update]
    
    # カテゴリー操作
    resources :operation_systems, only: [:create, :edit, :update, :destroy]
    resources :central_processing_units, only: [:create, :edit, :update, :destroy]
    resources :authentications, only: [:create, :edit, :update, :destroy]
    resources :specs, only: [:create, :edit, :update, :destroy]
    resources :makers, only: [:create, :edit, :update, :destroy]
    resources :capacities, only: [:create, :edit, :update, :destroy]
    
    get "search" => "searches#search"
  end
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # アソシエーション
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :interests, dependent: :destroy
  
  # バリデーション
  validates :name, presence: true, uniqueness: true
  
  # ゲストユーザー用メソッド
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # ログイン制限
  before_action :autheniticate_admin, only: [:index, :show, :edit]
  
  before_action :ensure_guest_user, only: [:edit]
  
  def index
    @users = User.all.page(params[:page]).per(10).order('id DESC')
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "会員情報の編集が完了しました。"
      redirect_to admin_user_path(@user.id)
    else
      flash[:danger] = "入力内容に不備があります。<br>・#{@user.errors.full_messages.join('<br>・')}"
      redirect_to request.referer
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
  
  # ゲストユーザーの会員情報を編集できないようにする
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "ゲストユーザー"
      flash[:warning] = "ゲストユーザーの会員情報は編集できません。"
      redirect_to request.referer
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/users/_index.html.erb
<table class="table bg-white">
  <thead class="bg-gainsboro">
    <th>ID</th>
    <th>名前</th>
    <th>登録日</th>
    <th>ステータス </th>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.name, admin_user_path(user.id) %></td>
        <td><%= user.created_at.strftime("%Y年%m月%d日") %></td>
        <td>
          <% if user.is_deleted == true %>
            <strong class="text-danger">退会済み</strong>
          <% else %>
            <strong class="text-secondary">利用中</strong>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mx-auto mt-3">
  <%= paginate users %>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  
  <div class="row border-bottom border-dark">
    <h2>会員情報変更</h2>
  </div>
  
  <p class="mt-4"><strong>></strong>下記の情報を入力してください</p>
  <%= render "layouts/flash" %>
  
  <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
    <table class="table border border-dark mt-3 shadow-sm">
      <thead class="thead-dark">
        <tr>
          <th class="text-white">基本登録情報</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody class="bg-white">
        <tr>
          <td class="col-3 bg-light text-right"><strong>名前</strong></td>
          <td class="col-6"><%= f.text_field :name, class: "form-control col-6" %></td>
          <td colspan=""></td>
        </tr>
        <tr>
          <td class="col-3 bg-light text-right"><strong>メールアドレス</strong></td>
          <td class="col-6"><%= f.email_field :email, class: "form-control" %></td>
          <td colspan=""></td>
        </tr>
        <tr>
          <td class="col-3 bg-light text-right"><strong>会員ステータス</strong></td>
          <td class="col-6">
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label  :is_deleted, "有効", value: false, class: "text-success mr-5" %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label  :is_deleted, "退会", value: true, class: "text-danger" %>
           </td>
          <td colspan=""></td>
        </tr>
      </tbody>
    </table>
    
    <div class="text-center mt-4">
      <%= f.submit "登録する", class: "font-weight-bold btn btn-lg btn-warning rounded-0" %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <%= form_with url: admin_search_path, local: true, method: :get, class: "search-form w-50" do |f| %>
      <div class="input-group">
        <%= f.text_field :word, class: "form-control", placeholder: "ユーザー名を入力" %>
        <%= f.submit "検索" %>
      </div>
    <% end %>
  </div>
  
  <div class="row mt-5">
    <%= render "admin/users/index", users: @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row border-bottom border-dark">
    <h3><strong>【<%= @user.name %>】さんの情報</strong></h3>
  </div>
  
  <div class="border border-dark mt-5">
    <table class="table  mb-0 bg-white">
      <tr>
        <th class="col-3">ユーザーID</th>
        <td class="col-9"><%= @user.id %></td>
      </tr>
      <tr>
        <th class="col-3">名前</th>
        <td class="col-9"><%= @user.name %></td>
      </tr>
      <tr>
        <th class="col-3">メールアドレス</th>
        <td class="col-9"><%= @user.email %></td>
      </tr>
      <tr>
        <th class="col-3">会員ステータス</th>
        <td class="col-9">
          <% if @user.is_deleted == false %>
            <span class="text-success">有効</span>
          <% else %>
            <span class="text-danger">退会済み</span>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  
  <div class="d-flex flex-column justify-content-center mt-5">
    <div class="mx-auto">
      <%= link_to "アカウント情報を編集する", edit_admin_user_path(@user.id), class: "font-weight-bold btn btn-warning rounded-0" %>
    </div>
    <div class="mx-auto mt-3">
      <%= render "layouts/flash" %>
    </div>
  </div>
  
  
</div>